name: mayr_dart_extensions
description: A comprehensive set of handy Dart extensions to make your code cleaner, shorter, and more expressive. Pure Dart package with zero Flutter dependencies.
version: 1.0.0
homepage: https://github.com/MayR-Labs/mayr_dart_extensions
repository: https://github.com/MayR-Labs/mayr_dart_extensions
issue_tracker: https://github.com/MayR-Labs/mayr_dart_extensions/issues
documentation: https://github.com/MayR-Labs/mayr_dart_extensions/wiki
license: MIT

environment:
  sdk: ^3.7.0

dependencies:
  get_time_ago: ^2.3.0
  intl: '>=0.18.0 <0.21.0'
  xml: ^6.5.0
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0

topics:
  - extensions
  - utilities
  - dart
  - productivity
  - toolkit
